### PR TITLE
getEventsのN+1解消

### PR DESCRIPTION
**Pull request by pinkumohikan**
refs #1

### CODE REVIEW

**Comment by pinkumohikan** [comment]
```
  "job_id": "",
  "ip_addrs": "35.74.254.73",
  "pass": true,
  "score": 20305,
  "message": "ok",
  "error": [
    "2021-07-10 10:34:15.648642868 +0000 UTC m=+49.538321599 Response code should be 204, got 403, data: <nil> (DELETE /api/events/11/sheets/C/57/reservation )",
    "2021-07-10 10:34:30.38038539 +0000 UTC m=+64.270064527 リクエストがタイムアウトしました (POST /api/events/11/actions/reserve )",
    "2021-07-10 10:34:32.004888008 +0000 UTC m=+65.894565704 リクエストがタイムアウトしました (GET /api/events/10 )",
    "2021-07-10 10:34:32.004890463 +0000 UTC m=+65.894568094 リクエストがタイムアウトしました (GET /api/users/3126 )",
    "2021-07-10 10:34:32.004896644 +0000 UTC m=+65.894574428 リクエストがタイムアウトしました (POST /api/events/11/actions/reserve )",
    "2021-07-10 10:34:32.00490989 +0000 UTC m=+65.894587586 リクエストがタイムアウトしました (POST /api/events/11/actions/reserve )",
    "2021-07-10 10:34:32.00494625 +0000 UTC m=+65.894623982 リクエストがタイムアウトしました (GET / )",
    "2021-07-10 10:34:32.004951592 +0000 UTC m=+65.894629267 リクエストがタイムアウトしました (GET /api/events/10 )",
    "2021-07-10 10:34:32.004967214 +0000 UTC m=+65.894645086 リクエストがタイムアウトしました (POST /api/events/11/actions/reserve )",
    "2021-07-10 10:34:32.004998158 +0000 UTC m=+65.894675878 リクエストがタイムアウトしました (GET / )"
  ],
```

**Comment by pinkumohikan** [comment]
```
{
  "job_id": "",
  "ip_addrs": "35.74.254.73",
  "pass": true,
  "score": 20411,
  "message": "ok",
  "error": [
    "2021-07-10 10:38:29.841448047 +0000 UTC m=+65.743192914 リクエストがタイムアウトしました (POST /api/events/11/actions/reserve )",
    "2021-07-10 10:38:29.841448279 +0000 UTC m=+65.743193202 リクエストがタイムアウトしました (DELETE /api/events/11/sheets/C/37/reservation )",
    "2021-07-10 10:38:29.841492694 +0000 UTC m=+65.743237621 リクエストがタイムアウトしました (GET /admin/ )",
    "2021-07-10 10:38:29.841526603 +0000 UTC m=+65.743271547 リクエストがタイムアウトしました (GET / )",
    "2021-07-10 10:38:29.84154761 +0000 UTC m=+65.743292520 リクエストがタイムアウトしました (GET / )",
    "2021-07-10 10:38:29.841569251 +0000 UTC m=+65.743314010 リクエストがタイムアウトしました (GET /api/users/3852 )",
    "2021-07-10 10:38:29.841629998 +0000 UTC m=+65.743374764 リクエストがタイムアウトしました (POST /api/events/11/actions/reserve )",
    "2021-07-10 10:38:29.841626734 +0000 UTC m=+65.743371826 リクエストがタイムアウトしました (GET /api/users/4107 )"
  ],
  "log": [
    "07/10 10:37:31 負荷レベルが上昇しました。",
    "07/10 10:37:32 負荷レベルが上昇しました。",
    "07/10 10:37:33 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4542",
    "07/10 10:37:34 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4542",
    "07/10 10:37:35 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4271",
    "07/10 10:37:36 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4930",
    "07/10 10:37:37 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4117",
    "07/10 10:37:38 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/815",
    "07/10 10:37:39 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/815",
    "07/10 10:37:40 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/815",
    "07/10 10:37:41 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/815",
    "07/10 10:37:42 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/815",
    "07/10 10:37:43 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3242",
    "07/10 10:37:44 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3242",
    "07/10 10:37:45 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/1931",
    "07/10 10:37:46 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2004",
    "07/10 10:37:47 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2004",
    "07/10 10:37:48 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2004",
    "07/10 10:37:49 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2004",
    "07/10 10:37:50 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4787",
    "07/10 10:37:51 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2072",
    "07/10 10:37:52 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3566",
    "07/10 10:37:53 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/77",
    "07/10 10:37:54 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/1822",
    "07/10 10:37:55 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2410",
    "07/10 10:37:56 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2410",
    "07/10 10:37:57 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:37:58 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:37:59 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3831",
    "07/10 10:38:00 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2891",
    "07/10 10:38:01 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2891",
    "07/10 10:38:02 レスポンスが遅いため負荷レベルを上げられませんでした。/admin/api/reports/sales",
    "07/10 10:38:03 レスポンスが遅いため負荷レベルを上げられませんでした。/admin/api/reports/sales",
    "07/10 10:38:04 レスポンスが遅いため負荷レベルを上げられませんでした。/admin/api/reports/events/10/sales",
    "07/10 10:38:05 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:06 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:07 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:08 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:09 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3006",
    "07/10 10:38:10 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/830",
    "07/10 10:38:11 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/830",
    "07/10 10:38:12 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:13 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:14 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:15 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/1373",
    "07/10 10:38:16 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:17 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:18 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:19 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:20 レスポンスが遅いため負荷レベルを上げられませんでした。/admin/",
    "07/10 10:38:21 レスポンスが遅いため負荷レベルを上げられませんでした。/admin/",
    "07/10 10:38:22 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3375",
    "07/10 10:38:23 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3375",
    "07/10 10:38:24 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/829",
    "07/10 10:38:25 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/829",
    "07/10 10:38:26 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3239",
    "07/10 10:38:27 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve",
    "07/10 10:38:28 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/10/sheets/C/265/reservation",
    "07/10 10:38:29 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/482"
  ],
  "load_level": 2,
  "start_time": "2021-07-10T10:37:24.247984196Z",
  "end_time": "2021-07-10T10:38:34.16692959Z"
}
```

app1 (app):
image


app2 (db):
image

**Comment by pinkumohikan** [comment]
うーん、調子が良いと予約APIでデッドロックが起きてfailしちゃうな...

> "status":500,"error":"Error 1213: Deadlock found when trying to get lock; try restarting transaction"

```
[  info ] [isu8q-bench] 2021/07/10 10:50:54.266888 bench.go:604: {"job_id":"","ip_addrs":"35.74.254.73","pass":false,"score":0,"message":"負荷走行中のバリデーションに失敗しました。2021-07-10 10:50:54.26663258 +0000 UTC m=+46.973258069 [Fatal]レポートに予約id:146270の行が存在しません (GET /admin/api/reports/events/10/sales )","error":["2021-07-10 10:50:34.92635075 +0000 UTC m=+27.632976241 サーバエラーが発生しました。500 Internal Server Error (POST /api/events/11/actions/reserve )","2021-07-10 10:50:34.935477279 +0000 UTC m=+27.642102825 サーバエラーが発生しました。500 Internal Server Error (POST /api/events/11/actions/reserve )","2021-07-10 10:50:34.936408719 +0000 UTC m=+27.643034241 サーバエラーが発生しました。500 Internal Server Error (POST /api/events/11/actions/reserve )","2021-07-10 10:50:41.121996223 +0000 UTC m=+33.828621867 Response code should be 204, got 403, data: \u003cnil\u003e (DELETE /api/events/11/sheets/C/342/reservation )","2021-07-10 10:50:54.26663258 +0000 UTC m=+46.973258069 [Fatal]レポートに予約id:146270の行が存在しません (GET /admin/api/reports/events/10/sales )"],"log":["07/10 10:50:14 負荷レベルが上昇しました。","07/10 10:50:15 レスポンスが遅いため負荷レベルを上げられませんでした。/admin/api/reports/sales","07/10 10:50:16 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/10/sheets/C/318/reservation","07/10 10:50:17 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/10/sheets/C/318/reservation","07/10 10:50:18 レスポンスが遅いため負荷レベルを上げられませんでした。/admin/api/reports/sales","07/10 10:50:19 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:20 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:21 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:22 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:23 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:24 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:25 負荷レベルが上昇しました。","07/10 10:50:26 負荷レベルが上昇しました。","07/10 10:50:27 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4094","07/10 10:50:28 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4583","07/10 10:50:29 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/10/actions/reserve","07/10 10:50:30 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:31 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:32 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/2140","07/10 10:50:33 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/1921","07/10 10:50:34 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:34.936408719 +0000 UTC m=+27.643034241 サーバエラーが発生しました。500 Internal Server Error (POST /api/events/11/actions/reserve )","07/10 10:50:35 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:34.936408719 +0000 UTC m=+27.643034241 サーバエラーが発生しました。500 Internal Server Error (POST /api/events/11/actions/reserve )","07/10 10:50:36 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:34.936408719 +0000 UTC m=+27.643034241 サーバエラーが発生しました。500 Internal Server Error (POST /api/events/11/actions/reserve )","07/10 10:50:37 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:34.936408719 +0000 UTC m=+27.643034241 サーバエラーが発生しました。500 Internal Server Error (POST /api/events/11/actions/reserve )","07/10 10:50:38 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:34.936408719 +0000 UTC m=+27.643034241 サーバエラーが発生しました。500 Internal Server Error (POST /api/events/11/actions/reserve )","07/10 10:50:39 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:40 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3662","07/10 10:50:41 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:41.121996223 +0000 UTC m=+33.828621867 Response code should be 204, got 403, data: \u003cnil\u003e (DELETE /api/events/11/sheets/C/342/reservation )","07/10 10:50:42 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:41.121996223 +0000 UTC m=+33.828621867 Response code should be 204, got 403, data: \u003cnil\u003e (DELETE /api/events/11/sheets/C/342/reservation )","07/10 10:50:43 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:41.121996223 +0000 UTC m=+33.828621867 Response code should be 204, got 403, data: \u003cnil\u003e (DELETE /api/events/11/sheets/C/342/reservation )","07/10 10:50:44 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:41.121996223 +0000 UTC m=+33.828621867 Response code should be 204, got 403, data: \u003cnil\u003e (DELETE /api/events/11/sheets/C/342/reservation )","07/10 10:50:45 エラーが発生したため負荷レベルを上げられませんでした。2021-07-10 10:50:41.121996223 +0000 UTC m=+33.828621867 Response code should be 204, got 403, data: \u003cnil\u003e (DELETE /api/events/11/sheets/C/342/reservation )","07/10 10:50:46 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:47 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:48 レスポンスが遅いため負荷レベルを上げられませんでした。/api/events/11/actions/reserve","07/10 10:50:49 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/191","07/10 10:50:50 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4122","07/10 10:50:51 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/4531","07/10 10:50:52 レスポンスが遅いため負荷レベルを上げられませんでした。/api/users/3162","07/10 10:50:53 レスポンスが遅いため負荷レベルを上げられませんでした。/admin/"],"load_level":0,"start_time":"2021-07-10T10:50:07.450789097Z","end_time":"2021-07-10T10:50:54.266733647Z"}
```

**Comment by mism-mism** [comment]
LGTM

**Pull request merged**
